CREATE TABLE users (
id int(11) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(55) NOT NULL,
email VARCHAR(255) NOT NULL,
pwd VARCHAR(255) NOT NULL,
role VARCHAR(55) NOT NULL,
Position VARCHAR(55) NOT NULL,
created_at timestamp DEFAULT CURRENT_DATE
);